version: '3.3'
services:
  db:
    image: postgres:15.2
    restart: always
    container_name: digital_vision_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_api
    ports:
     - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local